<a href="https://colab.research.google.com/github/fceller/neural-networks/blob/main/MatrixMultiplicationCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication and CNN

A junior class about matrices and neuronal networks.



## Vectors and ℝ^n

A vector in ℝ^n is a n-tuple of n real numbers. There are a lot of other possibilities like looking at complex numbers, integers, finite fields. For now, we will only look at real numbers.

### Example ℝ^2

Vectors are common noted as (x,y), sometimes as (x_0, x_1) if the number are keep variable. A single fixed vector is, for example, (1,2).

Vectors are elements of a vector space. This yields to a lot of other interesting interpretations. Ignore them for now. They are not (yet) important. For now, just think of vector is a sequence of n real numbers.

### Images

Consider your monitor. It's pictures is generated of millions of dots. Each indidual dots can be noted by (x,y) and has a brightness of b_x_y. If b_x_y = 0 it is black. If b_x_y = 255 it is white.

Let (0,0) identify first dot in the upper left corner and (639,479) the last dot in the lower right corner.

A picture can be described as a function f that takes a 2-dimensional vector as input and returns a number betweem 0 and 255.

f: ℝ^n => ℝ

However, there is also a different view on images and vectors.

Stay with the above example, it basically means that

(0,0) => b_0_0
(0,1) => b_0_1
...
(639,479) => b_639_479

An image can be described of map as above. It can also be described as an vector of length 640 x 480 = 307.200

(b_0_0, b_0_1, ..., b_639_479)

The image is representated as a huge vector of dot brightness values. Starting with the first row, followed by the second row and so on.

We will use this interpretation as an example in the following. However, let us start with a much smaller image. Assume you have 2x2 gray-scale image. Let us first set up some common python libraries and then create the corresponding 4-dimensional vector.

In [ ]:
%%capture
!pip3 install numpy
!pip3 install torch
!pip3 install networkx
!pip3 install matplotlib
!pip3 install scipy

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
image = [[255, 128], [64, 32]]
print(np.matrix(image))

[[255 128]
 [ 64  32]]


The image is very bright in the upper left corner and dark in the lower right one. Now create the corresponding 4-dimension image vector.

In [ ]:
image_vector = np.array([dot for lines in image for dot in lines])
print(image_vector)

[255 128  64  32]


## Vector multiplication

If you have TWO vectors you can “multiply” them as follows

(x0, x1, x2, x3) * (y0, y1, y2, y3)

Take the first numbers x0 and y0 and multiply them. Take the second and add the result to x0 * y0. In the end this will end up as

x0* y0 + x1 * y1 + x2 * y2 + x3 * y3

If you multiply two 4-dimensional vectors, you will end up with a single number!

### Example

Assume you want to compute the average brightness of an image. Then we can use vector multiplication as follows.

Define an "average" vector and multiply it with the image.

In [ ]:
avg = np.array([1/4, 1/4, 1/4, 1/4])
brightness = image_vector.dot(avg.T)
print(brightness)

119.75


So, the average is a bit below the average gray. If you do the multiplication "by hand" you will see that is the sum over all dots, normalized with a factor of 4 because there are in total 4 dots.

As a next step lets define two more "averaging" vectors. The first one puts a bias on the upper left corner. 

Note that, in an 2x2 this is a bit artificial. But let's stick to this easy example.

In [ ]:
ul = np.array([2/4,1/4,1/4,0])
brightness = image_vector.dot(ul.T)
print(brightness)

175.5


So, the upper left corner is much brighter than the average. Now look at the lower right corner.

In [ ]:
lr = np.array([0/4,1/4,1/4,2/4])
brightness = image_vector.dot(lr.T)
print(brightness)

64.0


Not that much suprisingly, the lower right corner is much darker.

## Matrics and ℝ^n

Now assume you have m vectors in ℝ^n. In the previous example three vectors. One vector to compute the average. One to compute the bias to the upper left corner. One to compute the bias to the lower left corner.

In the last example, we have three vectors in ℝ4 . This can be defined as a 4x3 matrix.

In [ ]:
all_avg = np.matrix([[1/4,1/4,1/4,1/4],[2/4,1/4,1/4,0/4],[0/4,1/4,1/4,2/4]])
print(all_avg)

[[0.25 0.25 0.25 0.25]
 [0.5  0.25 0.25 0.  ]
 [0.   0.25 0.25 0.5 ]]


This is called a 3x4 matrix. Ie. a list of three vectors of dimension 4.

A matrix multiplication is an generalization of the vector multiplication.

Take the image_vector and multiply this with the first column. Then the second column and so on.

However, the shape of the matrix does not "fit" to the vector. The first column has only 3 entries. We need to flip columns and rows. That is called transposing the matrix.

In [ ]:
all_t = all_avg.T
print(all_t)

[[0.25 0.5  0.  ]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.   0.5 ]]


We can now simple multiply the vector with the matrix.

In [ ]:
avgs = image_vector.dot(all_t)
print(avgs)

[[119.75 175.5   64.  ]]


We get all averages in one go.